In [1]:
%pip list


Package                 Version
----------------------- -----------
asttokens               3.0.1
colorama                0.4.6
comm                    0.2.3
contourpy               1.3.3
cycler                  0.12.1
debugpy                 1.8.20
decorator               5.2.1
executing               2.2.1
fonttools               4.62.1
ipykernel               7.2.0
ipython                 9.11.0
ipython_pygments_lexers 1.1.1
jedi                    0.19.2
joblib                  1.5.3
jupyter_client          8.8.0
jupyter_core            5.9.1
kiwisolver              1.5.0
matplotlib              3.10.8
matplotlib-inline       0.2.1
nest-asyncio            1.6.0
numpy                   2.4.3
packaging               26.0
pandas                  3.0.1
parso                   0.8.6
pillow                  12.1.1
pip                     25.1.1
platformdirs            4.9.4
prompt_toolkit          3.0.52
psutil                  7.2.2
pure_eval               0.2.3
Pygments                

In [2]:
print("hello")

hello


In [3]:
%ls

 Volume in drive C is OS
 Volume Serial Number is 3695-2DA4

 Directory of c:\Users\User\OneDrive\Attachments\Desktop\Machine Learning Course & Project

03/18/2026  02:05 PM    <DIR>          .
03/18/2026  01:57 PM    <DIR>          ..
03/18/2026  02:10 PM    <DIR>          .venv
03/18/2026  01:58 PM                 0 notebook_test.ipynb
03/18/2026  02:09 PM               191 test.py
               2 File(s)            191 bytes
               3 Dir(s)  30,154,604,544 bytes free


In [2]:
import time 
import numpy as np 
n = 1_000_000

py_list = list(range(n))
np_array = np.arange(n)

print(len(py_list))
print(len(np_array))

print(py_list[0:5])
print(np_array[0:5])

t1 = time.time()
py_result = [x * 2 for x in py_list]
t2 = time.time()

t3 = time.time()
np_result = np_array *2
t4 = time.time()

print("List time : ", t2-t1)
print("NumPy Time: ", t4-t3)

1000000
1000000
[0, 1, 2, 3, 4]
[0 1 2 3 4]
List time :  0.048929691314697266
NumPy Time:  0.0030782222747802734


In [6]:
import numpy as np
arr1 = np.array([1,2,3,4]) 
arr2 = np.array([[1,2,3],[4,5,6]])
arr3 = np.array([[[1,2,3], [4,5,6]],[[7,8,9],[10,11,12]]])

print("\n2D array : \n",arr2)
print("\n3D array : \n",arr3)


2D array : 
 [[1 2 3]
 [4 5 6]]

3D array : 
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [7]:
zeros = np.zeros((3,3))
ones = np.ones((3,2))
random_arr = np.random.rand(3,3)
eye = np.eye(3)
print(eye)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [12]:
np.random.seed(42)
np.random.randn(3, 3)  # normal distribution
np.random.rand(3, 3)   # uniform [0, 1)

array([[0.18182497, 0.18340451, 0.30424224],
       [0.52475643, 0.43194502, 0.29122914],
       [0.61185289, 0.13949386, 0.29214465]])

In [ ]:
id_arr = np.eye(4)
print(id_arr)

arr1 = np.arange(1,11,1) *10
print(arr1)



[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[ 10  20  30  40  50  60  70  80  90 100]


In [34]:
np.random.seed(0)
rand_arr = np.random.randn(3,3)
print(rand_arr)
print(rand_arr.shape, rand_arr.dtype,rand_arr.size)

[[ 1.76405235  0.40015721  0.97873798]
 [ 2.2408932   1.86755799 -0.97727788]
 [ 0.95008842 -0.15135721 -0.10321885]]
(3, 3) float64 9


In [52]:
arr = np.array([[10,30,20,],
               [40,50,60],
               [70,80,90]])

print(arr[0:2,1:])

mask = arr>50
print(arr[mask])

X = np.random.randn(100)
print(X[np.abs(X)<2])

[[30 20]
 [50 60]]
[60 70 80 90]
[-0.09815039  0.91017891  0.31721822  0.78632796 -0.4664191  -0.94444626
 -0.41004969 -0.01702041  0.37915174 -0.04225715 -0.955945   -0.34598178
 -0.46359597  0.48148147 -1.54079701  0.06326199  0.15650654  0.23218104
 -0.59731607 -0.23792173 -1.42406091 -0.49331988 -0.54286148  0.41605005
 -1.15618243  0.7811981   1.49448454  0.42625873  0.67690804 -0.63743703
 -0.39727181 -0.13288058 -0.29779088 -0.30901297 -1.67600381  1.15233156
  1.07961859 -0.81336426 -1.46642433  0.52106488 -0.57578797  0.14195316
 -0.31932842  0.69153875  0.69474914 -0.72559738 -1.38336396 -1.5829384
  0.61037938 -1.18885926 -0.50681635 -0.59631404 -0.0525673  -1.93627981
  0.1887786   0.52389102  0.08842209 -0.31088617  0.09740017  0.39904635
  1.95591231  0.39009332 -0.65240858 -0.39095338  0.49374178 -0.11610394
 -0.11054066  1.02017271 -0.69204985  1.53637705  0.28634369  0.60884383
 -1.04525337  1.21114529  0.68981816  1.30184623 -0.62808756 -0.48102712
 -1.06001582 -0.135

In [61]:
# Given: X = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
# Select: (a) the last 2 rows, (b) the middle column, (c) all values greater than 6.
X = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

print(X[-2:,])
print(X[:,1])
print(X[X>6])

[[ 7  8  9]
 [10 11 12]]
[ 2  5  8 11]
[ 7  8  9 10 11 12]


In [68]:
# Add a scalar to every element
arr = np.array([[1,2,3],[4,5,6]])
arr + 10     # adds 10 to everything

# Normalize each column by its mean
X = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])# 100 samples, 5 features
mean = X.mean(axis=0)        # shape (5,)
std  = X.std(axis=0)         # shape (5,)
X_norm = (X - mean) / std    # broadcasting! shape (100,5)
print(X_norm)
# ↑ This is feature normalization — used in every ML model

[[-1.34164079 -1.34164079 -1.34164079]
 [-0.4472136  -0.4472136  -0.4472136 ]
 [ 0.4472136   0.4472136   0.4472136 ]
 [ 1.34164079  1.34164079  1.34164079]]


In [71]:
X = np.array([[4,7,2],[1,8,3]])

X.sum()           # 25  (all)
X.sum(axis=0)     # [5, 15, 5]  (per column)
X.sum(axis=1)     # [13, 12]    (per row)
X.mean()          # 4.17
X.min(), X.max()  # 1, 8
X.argmax()        # 4  (flat index of max)
print(X.argmax(axis=1)) # [1, 1]  (col index of max per row)



[1 1]


In [80]:
# Create a 5x3 matrix of random floats, then: (a) normalize each column to have mean=0, std=1. (b) Find which row has the highest sum.
np.random.seed(1)
X = np.random.randn(5,3)
X_norm = (X - X.mean(axis = 0))/X.std(axis = 0)
print(X_norm.mean(axis = 0))
print(X_norm.std(axis =0))

[6.66133815e-17 2.22044605e-17 1.33226763e-16]
[1. 1. 1.]


In [86]:
A = np.array([[3.,1.],[1.,2.]])
A.T
np.linalg.det(A)
np.linalg.inv(A) 
vals, vecs = np.linalg.eig(A)
print(vals, vecs)

[3.61803399 1.38196601] [[ 0.85065081 -0.52573111]
 [ 0.52573111  0.85065081]]


In [ ]:
#Implement linear regression from scratch using only NumPy: given X (features) and y (labels), find weights w using the normal equation: w = (XᵀX)⁻¹ Xᵀy
X = np.random.randn(50, 2)
y = X @ np.array([2.0, 3.0]) + 0.1 * np.random.randn(50)

X_b = np.hstack([np.ones((50,1)),X])
print(X_b)
w = np.linalg.inv(X_b.T @ X_b) @ X_b.T @ y
print(w)

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 1 and the array at index 1 has size 2

In [ ]:
import numpy as np
a = np.arange(12)  

a.reshape(3, 4) 
a.reshape(2, 2, 3)
a.reshape(-1, 4) 
mat = np.ones((4, 3, 2))
mat.ravel()


array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1.])

In [1]:
import numpy as np
a = np.array([[1,2,3],[12,22,11]])
b = np.array([[4,5,6],[12,22,11]])
c = np.array([[7,8,9],[12,22,11]])

np.vstack([a, b,c])   # stack as rows → shape (2,3)
np.hstack([a, b,c])   # concat → shape (6,)


array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9],
       [12, 22, 11, 12, 22, 11, 12, 22, 11]])

In [4]:
np.random.seed(42)
X = np.random.randn(1000, 10)   # 1000 samples, 10 features
y = np.random.randint(0, 2, 1000)  # binary labels

# Shuffle
idx = np.random.permutation(len(X))
X, y = X[idx], y[idx]

# Split 80/10/10
n = len(X)
X_train, y_train = X[:800],  y[:800]
X_val,   y_val   = X[800:900], y[800:900]
X_test,  y_test  = X[900:],  y[900:]

# Mini-batch generator
def get_batches(X, y, batch_size=32):
    for i in range(0, len(X), batch_size):
        yield X[i:i+batch_size], y[i:i+batch_size]